name: Test Using Mocha

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        env:
          SECRET_VAR: ${{secrets.DATABASE_URL}}
        run: yarn test
