name: Test Using Mocha

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  NODE_ENV: "production"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Print variable
        run: echo $DATABASE_URL
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test
